flowchart TD
    B00 --> B01
    B00 --> B02
    B01 --> B02
    B02 --> B03
    B02 --> B04
    B02 --> B05
    B02 --> B06
    B02 --> B07
    B02 --> B08
    B01 --> B09
    B02 --> B09
    B03 --> B10
    B05 --> B10
    B06 --> B10
    B07 --> B10
    B02 --> B11
    B09 --> B11

    B03 --> T01
    B04 --> T01
    B05 --> T01
    B06 --> T01
    B07 --> T01
    B09 --> T01
    B10 --> T01

    T01 --> T02
    T02 --> T03
    B02 --> T04
    B08 --> T04
    B09 --> T04
    T01 --> T05
    T04 --> T05
    B10 --> T06
    T02 --> T06
    T03 --> T06
    B00 --> T07
    T04 --> T07
    T05 --> T07
    T02 --> T08
    T03 --> T08
    T06 --> T08
    T07 --> T08
    B03 --> T09
    T03 --> T09
    T08 --> T09
    T04 --> T10
    T05 --> T10
    T07 --> T10
    T08 --> T10
    T09 --> T10
